USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS GITPROJ_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


CREATE DATABASE IF NOT EXISTS GITPROJ;
CREATE SCHEMA IF NOT EXISTS GITPROJ.BRONZE;
CREATE SCHEMA IF NOT EXISTS GITPROJ.SILVER;
CREATE SCHEMA IF NOT EXISTS GITPROJ.GOLD;
CREATE SCHEMA IF NOT EXISTS GITPROJ.SNAPSHOTS;
CREATE SCHEMA IF NOT EXISTS GITPROJ.AI;

CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE ON WAREHOUSE GITPROJ_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE GITPROJ_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE GITPROJ TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE GITPROJ TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE GITPROJ TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE GITPROJ TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE GITPROJ TO ROLE DBT_ROLE;


SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER ($my_user);
SELECT 'setup complete' AS status;


