USE ROLE ACCOUNTADMIN;
USE DATABASE GITPROJ;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT GITPROJ.BRONZE.JSON_FMT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    TRIM_SPACE = FALSE
    NULL_IF = ('', '\\N', 'NULL')
    IGNORE_UTF8_ERRORS = TRUE;


CREATE OR REPLACE STAGE GITPROJ.BRONZE.GITPROJ_BRONZE_STAGE
    STORAGE_INTEGRATION = GITPROJ_S3_INT
    URL = 's3://github-repo-analytics-elt/raw/'
    FILE_FORMAT = GITPROJ.BRONZE.JSON_FMT

LIST @GITPROJ.BRONZE.GITPROJ_BRONZE_STAGE