USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION GITPROJ_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET_NAME>/raw');

GRANT USAGE ON INTEGRATION GITPROJ_S3_INT TO ROLE DBT_ROLE;

DESC INTEGRATION GITPROJ_S3_INT;